import {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_BLUE_COLOR,
  PRIMARY_BLACK_COLOR,
  SECONDARY_BLUE_COLOR,
} from "./StyleVariables";

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_BLUE_COLOR,
  PRIMARY_BLACK_COLOR,
  SECONDARY_BLUE_COLOR,
};
