import {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_BLUE_COLOR,
  PRIMARY_BLACK_COLOR,
  SECONDARY_BLUE_COLOR,
  BASIC_MOBILE_MEDIA_QUERY,
} from "./StyleVariables";

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_BLUE_COLOR,
  PRIMARY_BLACK_COLOR,
  SECONDARY_BLUE_COLOR,
  BASIC_MOBILE_MEDIA_QUERY,
};
